import { useMemo, useState } from 'react'
import { buildProgressEnvelope, formatProgressForAi } from '../ai/progressEnvelope'
import { AI_DESTINATIONS, readAiSharePreferences, saveAiSharePreferences } from '../storage/aiPreferences'
import type { AiSharePreferences } from '../storage/aiPreferences'

type AiSharingPageProps = { onBack: () => void }
function fallbackCopy(text: string) { const area = document.createElement('textarea'); area.value = text; area.style.position = 'fixed'; area.style.opacity = '0'; document.body.appendChild(area); area.select(); document.execCommand('copy'); area.remove() }

export function AiSharingPage({ onBack }: AiSharingPageProps) {
  const [preferences, setPreferences] = useState(readAiSharePreferences)
  const [status, setStatus] = useState('')
  const destination = AI_DESTINATIONS.find((item) => item.id === preferences.preferredDestination) ?? AI_DESTINATIONS[0]
  const envelope = useMemo(() => buildProgressEnvelope(preferences), [preferences])
  const text = useMemo(() => formatProgressForAi(envelope, destination.label), [destination.label, envelope])
  function update<K extends keyof AiSharePreferences>(key: K, value: AiSharePreferences[K]) { const next = { ...preferences, [key]: value }; setPreferences(next); saveAiSharePreferences(next); setStatus('Preferences saved on this device.') }
  async function copyText(value: string, message: string) { try { if (navigator.clipboard?.writeText) await navigator.clipboard.writeText(value); else fallbackCopy(value); setStatus(message) } catch { fallbackCopy(value); setStatus(message) } }
  async function shareProgress() { if (!navigator.share) { await copyText(text, `Copied. Paste it into ${destination.label} or another app.`); return } try { await navigator.share({ title: 'ShareCapsule Health progress', text }); setStatus('Progress shared through your device share sheet.') } catch (error) { if (error instanceof DOMException && error.name === 'AbortError') return; await copyText(text, `Sharing was unavailable, so the update was copied for ${destination.label}.`) } }
  function downloadJson() { const blob = new Blob([JSON.stringify(envelope, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `sharecapsule-health-progress-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); setStatus('Structured progress JSON downloaded.') }

  return (
    <main className="page-shell phase6-ai-page">
      <header className="subpage-header"><button className="icon-button" type="button" onClick={onBack} aria-label="Back to Progress">←</button><div><p className="eyebrow">Your progress, your assistant</p><h1>Share with AI</h1></div></header>
      <section className="settings-section phase6-destination"><p className="eyebrow">Destination</p><h2>Preferred app or AI</h2><p className="settings-intro">We remember your preference, but the browser/operating system controls which installed apps appear in the share sheet.</p><label><span><strong>Preferred destination</strong><small>Used to label and prepare your progress update.</small></span><select value={preferences.preferredDestination} onChange={(event) => update('preferredDestination', event.target.value as AiSharePreferences['preferredDestination'])}>{AI_DESTINATIONS.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label><span><strong>Progress period</strong><small>Choose how much local history to summarize.</small></span><select value={preferences.period} onChange={(event) => update('period', event.target.value as AiSharePreferences['period'])}><option value="today">Today</option><option value="7days">Last 7 days</option><option value="30days">Last 30 days</option><option value="all">All local history</option></select></label></section>
      <section className="settings-section"><p className="eyebrow">Privacy filter</p><h2>Choose what leaves this device</h2><p className="settings-intro">Nothing is sent automatically. These choices only affect the summary you explicitly share or copy.</p><label className="setting-row"><span><strong>Goals</strong><small>Daily targets and number of goal days.</small></span><input type="checkbox" checked={preferences.includeGoals} onChange={(event) => update('includeGoals', event.target.checked)} /></label><label className="setting-row"><span><strong>Streaks</strong><small>Current and best consistency streak.</small></span><input type="checkbox" checked={preferences.includeStreaks} onChange={(event) => update('includeStreaks', event.target.checked)} /></label><label className="setting-row"><span><strong>Daily breakdown</strong><small>Per-day activity count and minutes.</small></span><input type="checkbox" checked={preferences.includeDailyBreakdown} onChange={(event) => update('includeDailyBreakdown', event.target.checked)} /></label><label className="setting-row"><span><strong>Recent activity names</strong><small>Up to 10 recent activities and their duration.</small></span><input type="checkbox" checked={preferences.includeRecentActivities} onChange={(event) => update('includeRecentActivities', event.target.checked)} /></label><label className="setting-row"><span><strong>Confirmed check-ins</strong><small>Off by default. Shares only your confirmed mood labels and dates—not saved words or raw voice.</small></span><input type="checkbox" checked={preferences.includeCheckins} onChange={(event) => update('includeCheckins', event.target.checked)} /></label><label className="setting-row"><span><strong>Exact timestamps</strong><small>Off by default; otherwise shared items use only the local date.</small></span><input type="checkbox" checked={preferences.includeExactTimes} disabled={!preferences.includeRecentActivities && !preferences.includeCheckins} onChange={(event) => update('includeExactTimes', event.target.checked)} /></label></section>
      <section className="settings-section phase6-preview"><p className="eyebrow">Preview</p><h2>AI-ready progress update</h2><pre>{text}</pre><div className="phase6-share-actions"><button className="primary-button" type="button" onClick={shareProgress}>Share progress</button><button type="button" onClick={() => copyText(text, `Copied for ${destination.label}.`)}>Copy update</button><button type="button" onClick={() => copyText(JSON.stringify(envelope, null, 2), 'Structured progress JSON copied.')}>Copy JSON</button><button type="button" onClick={downloadJson}>Download JSON</button></div>{status ? <p className="phase6-status" role="status">{status}</p> : null}</section>
      <section className="settings-section settings-privacy"><p className="eyebrow">Connector-ready</p><h2>One progress contract for any AI</h2><p>The JSON uses the versioned <code>sharecapsule.health.progress.v1</code> contract. Confirmed check-ins are optional and remain user-controlled.</p></section>
    </main>
  )
}
