type PrivacyPageProps = { onBack: () => void }

export function PrivacyPage({ onBack }: PrivacyPageProps) {
  return (
    <main className="page-shell phase5-privacy-page">
      <header className="subpage-header"><button className="icon-button" type="button" onClick={onBack} aria-label="Back to Settings">←</button><div><p className="eyebrow">ShareCapsule Health</p><h1>Privacy</h1></div></header>
      <section className="settings-section"><p className="eyebrow">Current PWA</p><h2>Local-first wellness data</h2><p>Activity history, favorites, goals, routines, schedules, preferences and confirmed wellness check-ins are stored in this browser's local storage. The current PWA does not require a ShareCapsule account or upload this wellness history to a ShareCapsule server.</p></section>
      <section className="settings-section"><p className="eyebrow">Voice check-in</p><h2>Your voice is for your answer, not hidden profiling</h2><p>The app may use your browser/device speech-recognition feature after you explicitly start a voice answer. ShareCapsule Health does not store raw microphone audio and does not infer mood from vocal tone, pitch or other biometric voice characteristics. It may suggest a label only when your transcribed words explicitly describe how you feel, and nothing is saved until you confirm a label. Browser speech recognition may be processed according to your browser or operating-system provider's terms.</p></section>
      <section className="settings-section"><p className="eyebrow">Check-in words</p><h2>Transcript saving is optional</h2><p>Saving your spoken or typed words is off by default. When it is off, a check-in stores only your confirmed label, timestamp and whether the input began as voice or text.</p></section>
      <section className="settings-section"><p className="eyebrow">AI & app sharing</p><h2>Nothing is sent automatically</h2><p>When you use Share with AI, ShareCapsule Health builds a progress summary locally from the fields you selected. Confirmed check-ins are excluded by default and can be added only with a separate toggle. Saved check-in words and raw voice are never included in the current progress payload.</p></section>
      <section className="settings-section"><p className="eyebrow">AI progress contract</p><h2>Summary data, not raw health records</h2><p>The current <code>sharecapsule.health.progress.v1</code> payload contains wellness activity totals and optional goals, streaks, daily summaries, recent activity names and user-confirmed check-in labels. It does not contain HealthKit/Health Connect raw samples, medical records, device identifiers, raw voice or verified step records.</p></section>
      <section className="settings-section"><p className="eyebrow">Notifications</p><h2>You stay in control</h2><p>Browser notification permission is optional. Routine reminder schedules are stored locally. Your operating system and browser control how system notifications, sounds and vibration are presented.</p></section>
      <section className="settings-section"><p className="eyebrow">Health data</p><h2>No step or medical-record access yet</h2><p>This PWA does not currently read Apple HealthKit, Android Health Connect, wearable step data or medical records. Any future verified-step or competition feature will require a separate native integration and explicit permission.</p></section>
      <section className="settings-section"><p className="eyebrow">Your controls</p><h2>Export or remove local data</h2><p>Settings provides controls to download a JSON backup, restore a compatible backup, or clear ShareCapsule Health data from this browser.</p></section>
      <section className="settings-section settings-privacy"><p className="eyebrow">Wellness scope</p><h2>Not medical treatment</h2><p>ShareCapsule Health provides general wellness activities and self-report check-ins. It is not a diagnostic or treatment service and is not a substitute for professional medical care.</p></section>
    </main>
  )
}
